import sukiyaki from './images/image-list/sukiyaki.jpg';
import french_toast from './images/image-list/french-toast.jpg';
import yakisoba from './images/image-list/yakisoba.jpg';
import yakitori from './images/image-list/yakitori.jpg';
import birthday_cake from './images/image-list/birthday-cake.jpg';
import napolitan_pasta from './images/image-list/napolitan-pasta.jpg';
import omurice from './images/image-list/omurice.jpg';
import katsu_curry from './images/image-list/katsu-curry.jpg';
import bento from './images/image-list/bento.jpg';
import hamburguer from './images/image-list/hamburguer.jpg';
import oyakodon from './images/image-list/oyakodon.jpg';

const itemData = [
  {
    img: sukiyaki,
    title: 'すき焼き (Sukiyaki)',
    price: '5,000円',
    videoId: '1Ed8GLLJJHk',
    modalCols: 4,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: french_toast,
    title: 'フレンチトースト (French toast)',
    price: '????',
    videoId: 'UZdP0fDG8cg',
    modalCols: 4,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: yakisoba,
    title: '焼きそば (Yakisoba)',
    price: '2,000円',
    videoId: 'mbkE_SqVR58',
    modalCols: 5,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: yakitori,
    title: '焼き鳥 (Yakitori)',
    price: '500円',
    videoId: 'OdYSQ_I7gYQ',
    modalCols: 5,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: birthday_cake,
    title: '誕生日ケーキ (Birthday cake)',
    price: '????',
    videoId: 'ITC4esgZbAA',
    modalCols: 5,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: napolitan_pasta,
    title: 'ナポリタン (Napolitan pasta)',
    price: '????',
    videoId: 'N-jbTbpLOJU',
    modalCols: 4,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: omurice,
    title: 'オムライス (Omurice)',
    price: '????',
    videoId: 'KNYf-ym6W-k',
    modalCols: 4,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: katsu_curry,
    title: 'カツカレー (Katsukare)',
    price: '????',
    videoId: 'Z6wMEJf8wJk',
    modalCols: 5,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: bento,
    title: 'お弁当 (Bento)',
    price: '????',
    videoId: 'Om-HYEPV1O4',
    modalCols: 5,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: hamburguer,
    title: 'ハンバーガー (Hamburguer)',
    price: '????',
    videoId: '4MdM34zBqI8',
    modalCols: 4,
    recipeCard: false,
    ingredientsEN: [],
    ingredientsJP: [],
    stepsEN: [],
    stepsJP: [],
  },
  {
    img: oyakodon,
    title: '親子丼 (Oyakdon)',
    price: '????',
    videoId: 'dMYMXT6uGrY',
    modalCols: 4,
    recipeCard: true,
    ingredientsEN: [
      { name: '1 Large Onion' },
      { name: 'Chicken breast or thigh meat' },
      { name: '2 Large Eggs' },
      { name: '1 Spring Onion' },
      { name: 'Soy Sauce' },
      { name: 'Cooking oil' },
      { name: 'Rice' },
    ],
    ingredientsJP: [],
    stepsEN: [
      { step: 'Slice 1/2 a Large onion', time: 652 },
      { step: 'Warm the pan', time: 771 },
      { step: 'Slice a Spring Onion', time: 804 },
      { step: 'Fry Chicken in the pan turning until cooked', time: 864 },
      { step: 'Slice the Chicken into smaller chunks', time: 1128 },
      { step: 'To make the sauce combine: 1 spoon of Oil, 1 spoon Soy Sauce and 1 spoon Water', time: 1219 },
      { step: 'Add the sliced Large Onion to the pan and cook', time: 1322 },
      { step: 'Add one more spoon of Soy Sauce', time: 1445 },
      { step: 'Add the cooked Chicken back to the pot', time: 1486 },
      { step: 'Add one more spoon of Water if its starting to dry', time: 1520 },
      { step: 'Crack 1 Egg in beaker, swirl 3 times to mix and then add to pot.', time: 1716 },
      { step: 'Cook for 1 minute on low heat', time: 1779 },
      { step: 'Repeat step 11 with another egg. Then add the Spring Onions.', time: 1944 },
      { step: 'Cook a portion of Rice, add to pot and mix', time: 2074 },
    ],
    stepsJP: []
  },
];

export default itemData;